### ISSUE TITLE
Pipeline failure in docker in align.py post_process step

### ISSUE THREAD

**Issue by robes** [ENCODE-DCC/rna-seq-pipeline#15]
I am trying to use the rna-seq-pipeline per the howto guide for "Local with Docker." When I get to step 4, "Run the pipeline":

```
$ java -jar -Dconfig.file=backends/backend.conf cromwell-34.jar run rna-seq-pipeline.wdl -i input.json -o workflow_opts/docker.json
```

The workflow fails consistently at this point.
```
...
[2019-03-18 15:58:24,30] [error] WorkflowManagerActor Workflow 358f5788-fd45-4d55-9373-2cb266f28ee3 failed (during ExecutingWorkflowState): Job rna.align:1:1 exited with return code 1 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details.
Check the content of stderr for potential additional information: /Users/schuler/devel/encode-dcc/rna-seq-pipeline/cromwell-executions/rna/358f5788-fd45-4d55-9373-2cb266f28ee3/call-align/shard-1/execution/stderr.
 2019-03-18 22:57:35,904 | INFO | __main__: Creating a single-ended aligner.
2019-03-18 22:57:35,910 | INFO | __main__: running STAR command STAR --genomeDir out --readFilesIn /cromwell-executions/rna/358f5788-fd45-4d55-9373-2cb266f28ee3/call-align/shard-1/inputs/-1048443674/rep2_ENCSR510QZW_chr19only_10000_reads.fastq.gz --readFilesCommand zcat --runThreadN 2 --genomeLoad NoSharedMemory --outFilterMultimapNmax 20 --alignSJoverhangMin 8 --alignSJDBoverhangMin 1 --outFilterMismatchNmax 999 --outFilterMismatchNoverReadLmax 0.04 --alignIntronMin 20 --alignIntronMax 1000000 --alignMatesGapMax 1000000 --outSAMheaderCommentFile COfile.txt --outSAMheaderHD @HD VN:1.4 SO:coordinate --outSAMunmapped Within --outFilterType BySJout --outSAMattributes NH HI AS NM MD --outSAMstrandField intronMotif --outSAMtype BAM SortedByCoordinate --quantMode TranscriptomeSAM --sjdbScore 1 --limitBAMsortRAM 4000000000
Traceback (most recent call last):
  File "/software/rna-seq-pipeline/src/align.py", line 275, in <module>
    main(args)
  File "/software/rna-seq-pipeline/src/align.py", line 219, in main
    aligner.post_process()
  File "/software/rna-seq-pipeline/src/align.py", line 108, in post_process
    os.path.join(cwd, self.bamroot + '_Log.final.out'))
FileNotFoundError: [Errno 2] No such file or directory: '/cromwell-executions/rna/358f5788-fd45-4d55-9373-2cb266f28ee3/call-align/shard-1/execution/Log.final.out' -> '/cromwell-executions/rna/358f5788-fd45-4d55-9373-2cb266f28ee3/call-align/shard-1/execution/rep2SE_unstranded_Log.final.out'

[2019-03-18 15:58:24,30] [info] WorkflowManagerActor WorkflowActor-358f5788-fd45-4d55-9373-2cb266f28ee3 is in a terminal state: WorkflowFailedState
...
```

I looked at `src\align.py` line 108. The log file it is trying to rename at that step just doesn't exist in my cromwell-execution subdir for that run.

FWIW, I'm running:
- Docker Desktop Community Version 2.0.0.3
- MacOS 10.14.3
- Java version 1.8.0_102
- cromwell release 34 (I did also try with the latest release, 38, same results)

About me:
I work on the FaceBase DCC (www.facebase.org). We are already using the ENCODE-DCC rna-seq and chip-seq pipelines on DNAnexus and we now would like to have the option to run them locally with your docker containers.

**Comment by ottojolanki** [comment]
Hi robes,
I cannot seem to reproduce the problem. Could show me the `input.json` you are using?

**Comment by robes** [comment]
Sure:
```
{
    "rna.endedness" : "single",
    "rna.fastqs_R1" : ["/Users/schuler/devel/encode-dcc/rna-seq-pipeline/test_data/rep1_ENCSR510QZW_chr19only_10000_reads.fastq.gz","/Users/schuler/devel/encode-dcc/rna-seq-pipeline/test_data/rep2_ENCSR510QZW_chr19only_10000_reads.fastq.gz"],
    "rna.aligner" : "star",
    "rna.bamroot" : "SE_unstranded",
    "rna.align_index" : "/Users/schuler/devel/encode-dcc/rna-seq-pipeline/test_data/GRCh38_v24_ERCC_phiX_starIndex_chr19only.tgz",
    "rna.rsem_index" : "/Users/schuler/devel/encode-dcc/rna-seq-pipeline/test_data/GRCh38_v24_ERCC_phiX_rsemIndex_chr19only.tgz",
    "rna.kallisto_index" : "/Users/schuler/devel/encode-dcc/rna-seq-pipeline/test_data/Homo_sapiens.GRCh38.cdna.all.chr19_ERCC_phix_k31_kallisto.idx",
    "rna.strandedness" : "unstranded",
    "rna.strandedness_direction" : "unstranded",
    "rna.chrom_sizes" : "/Users/schuler/devel/encode-dcc/rna-seq-pipeline/test_data/GRCh38_EBV.chrom.sizes",
    "rna.align_ncpus" : 2,
    "rna.align_ramGB" : 4,
    "rna.rsem_ncpus" : 2,
    "rna.rsem_ramGB" : 4,
    "rna.kallisto_number_of_threads" : 2,
    "rna.kallisto_ramGB" : 4,
    "rna.kallisto_fragment_length" : 250,
    "rna.kallisto_sd_of_fragment_length" : 10,
    "rna.rna_qc_tr_id_to_gene_type_tsv" : "/Users/schuler/devel/encode-dcc/rna-seq-pipeline/transcript_id_to_gene_type_mappings/gencodeV24pri-tRNAs-ERCC-phiX.transcript_id_to_genes.tsv",
    "rna.bam_to_signals_ncpus" : 1,
    "rna.bam_to_signals_ramGB" : 2,
    "rna.align_disk" : "local-disk 20 HDD",
    "rna.kallisto_disk" : "local-disk 20 HDD",
    "rna.rna_qc_disk" : "local-disk 20 HDD",
    "rna.bam_to_signals_disk" : "local-disk 20 HDD",
    "rna.mad_qc_disk" : "local-disk 20 HDD",
    "rna.rsem_disk" : "local-disk 20 HDD"
}
```

**Comment by ottojolanki** [comment]
Hmm, this is kind of mysterious. I am running basically the same system you are and everything works. My docker desktop version is exactly the same as yours. This is probably not important (we have been running with several different dockers and have not seen significant differences), but could you see what your `docker version` outputs. Mine looks like this:

```bash
DN0a22f320:rna-seq-pipeline otto$ docker version
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

Also looks like you are running the command line in the `rna-seq-pipeline` folder (as you should) and have not moved stuff around?

**Comment by robes** [comment]
Here's docker version:
```
$ docker version
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

And that's correct, I'm running the command from the `rna-seq-pipeline` directory and I haven't altered anything.

**Comment by ottojolanki** [comment]
It may be that your docker engine does not have enough memory allocated to it. Go to your docker preferences and then go to Advanced tab. Docker should have at least 8.0GiB available. I think I have seen STAR fail quietly in some not enough memory type of situations.

**Comment by robes** [comment]
You are right! Mine was set at the installed default which was a tiny 2.0GiB. I increased it to 16GiB and it appears to have run successfully. Thank you.
