### ISSUE TITLE
STAR error for replicates stranded test data

### ISSUE THREAD

**Issue by SooLee** [ENCODE-DCC/rna-seq-pipeline#39]
I'm getting this error while running STAR with the PE stranded replicate data provided in the test example. Am I missing something?

```
running STAR command STAR --genomeDir out --readFilesIn /cromwell-executions/rna/3052ae67-86b5-4562-a855-dfbf3845e10d/call-align/shard-1/inputs/-1248700713/ENCSR653DFZ_rep2_chr19_10000reads_R1.fastq.gz /cromwell-executions/rna/3052ae67-86b5-4562-a855-dfbf3845e10d/call-align/shard-1/inputs/-1248700713/ENCSR653DFZ_rep2_chr19_10000reads_R2.fastq.gz --readFilesCommand zcat --runThreadN 8 --genomeLoad NoSharedMemory --outFilterMultimapNmax 20 --alignSJoverhangMin 8 --alignSJDBoverhangMin 1 --outFilterMismatchNmax 999 --outFilterMismatchNoverReadLmax 0.04 --alignIntronMin 20 --alignIntronMax 1000000 --alignMatesGapMax 1000000 --outSAMheaderCommentFile COfile.txt --outSAMheaderHD @HD VN:1.4 SO:coordinate --outSAMunmapped Within --outFilterType BySJout --outSAMattributes NH HI AS NM MD --outSAMtype BAM SortedByCoordinate --quantMode TranscriptomeSAM --sjdbScore 1 --limitBAMsortRAM 8000000000
Traceback (most recent call last):
  File "/software/rna-seq-pipeline/src/align.py", line 275, in <module>
    main(args)
  File "/software/rna-seq-pipeline/src/align.py", line 219, in main
    aligner.post_process()
  File "/software/rna-seq-pipeline/src/align.py", line 108, in post_process
    os.path.join(cwd, self.bamroot + '_Log.final.out'))
FileNotFoundError: [Errno 2] No such file or directory: '/cromwell-executions/rna/3052ae67-86b5-4562-a855-dfbf3845e10d/call-align/shard-1/execution/Log.final.out' -> '/cromwell-executions/rna/3052ae67-86b5-4562-a855-dfbf3845e10d/call-align/shard-1/execution/rep2PE_stranded_Log.final.out'
```

**Comment by ottojolanki** [comment]
Could you check how much memory you have allowed your docker engine to use?

**Comment by SooLee** [comment]
I reran the whole pipeline with 120G mem and it succeeded. It had failed with 32G.
