### ISSUE TITLE
Work flow fail,

### ISSUE THREAD

**Issue by wpratcher** [ENCODE-DCC/rna-seq-pipeline#53]
I have been continuing to have issues with the set of code to make the test data work. here is the full run result I keep getting: 

2020-02-27 14:19:32,198  INFO  - Workflow polling stopped
2020-02-27 14:19:32,215  INFO  - 0 workflows released by cromid-4812e0e
2020-02-27 14:19:32,217  INFO  - Shutting down WorkflowStoreActor - Timeout = 5 seconds
2020-02-27 14:19:32,220  INFO  - Shutting down WorkflowLogCopyRouter - Timeout = 5 seconds
2020-02-27 14:19:32,222  INFO  - Shutting down JobExecutionTokenDispenser - Timeout = 5 seconds
2020-02-27 14:19:32,224  INFO  - JobExecutionTokenDispenser stopped
2020-02-27 14:19:32,228 cromwell-system-akka.dispatchers.engine-dispatcher-35 INFO  - Aborting all running workflows.
2020-02-27 14:19:32,229  INFO  - WorkflowStoreActor stopped
2020-02-27 14:19:32,234  INFO  - WorkflowLogCopyRouter stopped
2020-02-27 14:19:32,234  INFO  - Shutting down WorkflowManagerActor - Timeout = 3600 seconds
2020-02-27 14:19:32,235 cromwell-system-akka.dispatchers.engine-dispatcher-99 INFO  - WorkflowManagerActor All workflows finished
2020-02-27 14:19:32,236  INFO  - WorkflowManagerActor stopped
2020-02-27 14:19:32,845  INFO  - Connection pools shut down
2020-02-27 14:19:32,848  INFO  - Shutting down SubWorkflowStoreActor - Timeout = 1800 seconds
2020-02-27 14:19:32,848  INFO  - Shutting down JobStoreActor - Timeout = 1800 seconds
2020-02-27 14:19:32,848  INFO  - Shutting down CallCacheWriteActor - Timeout = 1800 seconds
2020-02-27 14:19:32,848  INFO  - Shutting down ServiceRegistryActor - Timeout = 1800 seconds
2020-02-27 14:19:32,848  INFO  - Shutting down DockerHashActor - Timeout = 1800 seconds
2020-02-27 14:19:32,848  INFO  - Shutting down IoProxy - Timeout = 1800 seconds
2020-02-27 14:19:32,848  INFO  - SubWorkflowStoreActor stopped
2020-02-27 14:19:32,854  INFO  - IoProxy stopped
2020-02-27 14:19:32,854  INFO  - JobStoreActor stopped
2020-02-27 14:19:32,856  INFO  - CallCacheWriteActor Shutting down: 0 queued messages to process
2020-02-27 14:19:32,856  INFO  - KvWriteActor Shutting down: 0 queued messages to process
2020-02-27 14:19:32,857  INFO  - CallCacheWriteActor stopped
2020-02-27 14:19:32,857  INFO  - WriteMetadataActor Shutting down: 0 queued messages to process
2020-02-27 14:19:32,858  INFO  - DockerHashActor stopped
2020-02-27 14:19:32,866  INFO  - ServiceRegistryActor stopped
2020-02-27 14:19:32,904  INFO  - Database closed
2020-02-27 14:19:32,904  INFO  - Stream materializer shut down
2020-02-27 14:19:32,905  INFO  - WDL HTTP import resolver closed
Workflow 504acb6a-03c0-4bc5-ab1c-af345eeb427a transitioned to state Failed
2020-02-27 14:19:32,970  INFO  - Shutting down connection pool: curAllocated=0 idleQueues.size=0 waitQueue.size=0 maxWaitQueueLimit=256 closed=false
2020-02-27 14:19:32,970  INFO  - Shutting down connection pool: curAllocated=0 idleQueues.size=0 waitQueue.size=0 maxWaitQueueLimit=256 closed=false
2020-02-27 14:19:32,970  INFO  - Shutting down connection pool: curAllocated=0 idleQueues.size=0 waitQueue.size=0 maxWaitQueueLimit=256 closed=false
2020-02-27 14:19:32,970  INFO  - Shutting down connection pool: curAllocated=0 idleQueues.size=0 waitQueue.size=0 maxWaitQueueLimit=256 closed=false
[CaperURI] write to local, target: /wynton/home/ahituv/wpratcher/rna-seq-pipeline/rna-seq-pipeline/504acb6a-03c0-4bc5-ab1c-af345eeb427a/metadata.json, size: 56876
[Caper] troubleshooting 504acb6a-03c0-4bc5-ab1c-af345eeb427a ...
Found failures:
[
    {
        "message": "Workflow failed",
        "causedBy": [
            {
                "message": "Failed to evaluate job outputs",
                "causedBy": [
                    {
                        "message": "Bad output 'kallisto.quants': Failed to find index Success(WomInteger(0)) on array:\n\nSuccess([])\n\n0",
                        "causedBy": []
                    },
                    {
                        "causedBy": [],
                        "message": "Bad output 'kallisto.python_log': Failed to find index Success(WomInteger(0)) on array:\n\nSuccess([])\n\n0"
                    }
                ]
            },
            {
                "causedBy": [
                    {
                        "causedBy": [],
                        "message": "Bad output 'kallisto.quants': Failed to find index Success(WomInteger(0)) on array:\n\nSuccess([])\n\n0"
                    },
                    {
                        "causedBy": [],
                        "message": "Bad output 'kallisto.python_log': Failed to find index Success(WomInteger(0)) on array:\n\nSuccess([])\n\n0"
                    }
                ],
                "message": "Failed to evaluate job outputs"
            },
            {
                "message": "Failed to evaluate job outputs",
                "causedBy": [
                    {
                        "causedBy": [],
                        "message": "Bad output 'align.genomebam': Failed to find index Success(WomInteger(0)) on array:\n\nSuccess([])\n\n0"
                    },
                    {
                        "causedBy": [],
                        "message": "Bad output 'align.annobam': Failed to find index Success(WomInteger(0)) on array:\n\nSuccess([])\n\n0"
                    },
                    {
                        "message": "Bad output 'align.genome_flagstat': Failed to find index Success(WomInteger(0)) on array:\n\nSuccess([])\n\n0",
                        "causedBy": []
                    },
                    {
                        "causedBy": [],
                        "message": "Bad output 'align.anno_flagstat': Failed to find index Success(WomInteger(0)) on array:\n\nSuccess([])\n\n0"
                    },
                    {
                        "causedBy": [],
                        "message": "Bad output 'align.log': Failed to find index Success(WomInteger(0)) on array:\n\nSuccess([])\n\n0"
                    },
                    {
                        "causedBy": [],
                        "message": "Bad output 'align.genome_flagstat_json': Failed to find index Success(WomInteger(0)) on array:\n\nSuccess([])\n\n0"
                    },
                    {
                        "message": "Bad output 'align.anno_flagstat_json': Failed to find index Success(WomInteger(0)) on array:\n\nSuccess([])\n\n0",
                        "causedBy": []
                    },
                    {
                        "message": "Bad output 'align.log_json': Failed to find index Success(WomInteger(0)) on array:\n\nSuccess([])\n\n0",
                        "causedBy": []
                    },
                    {
                        "message": "Bad output 'align.python_log': Failed to find index Success(WomInteger(0)) on array:\n\nSuccess([])\n\n0",
                        "causedBy": []
                    }
                ]
            },
            {
                "message": "Failed to evaluate job outputs",
                "causedBy": [
                    {
                        "causedBy": [],
                        "message": "Bad output 'align.genomebam': Failed to find index Success(WomInteger(0)) on array:\n\nSuccess([])\n\n0"
                    },
                    {
                        "causedBy": [],
                        "message": "Bad output 'align.annobam': Failed to find index Success(WomInteger(0)) on array:\n\nSuccess([])\n\n0"
                    },
                    {
                        "causedBy": [],
                        "message": "Bad output 'align.genome_flagstat': Failed to find index Success(WomInteger(0)) on array:\n\nSuccess([])\n\n0"
                    },
                    {
                        "causedBy": [],
                        "message": "Bad output 'align.anno_flagstat': Failed to find index Success(WomInteger(0)) on array:\n\nSuccess([])\n\n0"
                    },
                    {
                        "message": "Bad output 'align.log': Failed to find index Success(WomInteger(0)) on array:\n\nSuccess([])\n\n0",
                        "causedBy": []
                    },
                    {
                        "causedBy": [],
                        "message": "Bad output 'align.genome_flagstat_json': Failed to find index Success(WomInteger(0)) on array:\n\nSuccess([])\n\n0"
                    },
                    {
                        "causedBy": [],
                        "message": "Bad output 'align.anno_flagstat_json': Failed to find index Success(WomInteger(0)) on array:\n\nSuccess([])\n\n0"
                    },
                    {
                        "causedBy": [],
                        "message": "Bad output 'align.log_json': Failed to find index Success(WomInteger(0)) on array:\n\nSuccess([])\n\n0"
                    },
                    {
                        "causedBy": [],
                        "message": "Bad output 'align.python_log': Failed to find index Success(WomInteger(0)) on array:\n\nSuccess([])\n\n0"
                    }
                ]
            }
        ]
    }
]

rna.align Failed. SHARD_IDX=0, RC=None, JOB_ID=5320, RUN_START=2020-02-27T22:15:28.492Z, RUN_END=2020-02-27T22:18:58.756Z, STDOUT=/wynton/home/ahituv/wpratcher/rna-seq-pipeline/rna/504acb6a-03c0-4bc5-ab1c-af345eeb427a/call-align/shard-0/execution/stdout, STDERR=/wynton/home/ahituv/wpratcher/rna-seq-pipeline/rna/504acb6a-03c0-4bc5-ab1c-af345eeb427a/call-align/shard-0/execution/stderr
STDERR_CONTENTS=
2020-02-27 14:16:34,955 | INFO | __main__: Creating a single-ended aligner.
2020-02-27 14:16:34,988 | INFO | __main__: running STAR command STAR --genomeDir out --readFilesIn /wynton/home/ahituv/wpratcher/rna-seq-pipeline/rna/504acb6a-03c0-4bc5-ab1c-af345eeb427a/call-align/shard-0/inputs/-945160394/rep1_ENCSR510QZW_chr19only_10000_reads.fastq.gz --readFilesCommand zcat --runThreadN 2 --genomeLoad NoSharedMemory --outFilterMultimapNmax 20 --alignSJoverhangMin 8 --alignSJDBoverhangMin 1 --outFilterMismatchNmax 999 --outFilterMismatchNoverReadLmax 0.04 --alignIntronMin 20 --alignIntronMax 1000000 --alignMatesGapMax 1000000 --outSAMheaderCommentFile COfile.txt --outSAMheaderHD @HD VN:1.4 SO:coordinate --outSAMunmapped Within --outFilterType BySJout --outSAMattributes NH HI AS NM MD --outSAMstrandField intronMotif --outSAMtype BAM SortedByCoordinate --quantMode TranscriptomeSAM --sjdbScore 1 --limitBAMsortRAM 4000000000
2020-02-27 14:17:25,919 | INFO | __main__: Transcriptome bam is not rsem-sorted.
2020-02-27 14:17:25,936 | INFO | __main__: Running convert-sam-for-rsem Aligned.toTranscriptome.out.bam rep1SE_unstranded_anno
2020-02-27 14:17:27,612 | INFO | __main__: Getting samtools flagstats for /wynton/home/ahituv/wpratcher/rna-seq-pipeline/rna/504acb6a-03c0-4bc5-ab1c-af345eeb427a/call-align/shard-0/execution/rep1SE_unstranded_genome.bam
2020-02-27 14:17:27,673 | INFO | __main__: Getting samtools flagstats for /wynton/home/ahituv/wpratcher/rna-seq-pipeline/rna/504acb6a-03c0-4bc5-ab1c-af345eeb427a/call-align/shard-0/execution/rep1SE_unstranded_anno.bam

rna.align Failed. SHARD_IDX=1, RC=None, JOB_ID=4951, RUN_START=2020-02-27T22:15:22.806Z, RUN_END=2020-02-27T22:18:56.671Z, STDOUT=/wynton/home/ahituv/wpratcher/rna-seq-pipeline/rna/504acb6a-03c0-4bc5-ab1c-af345eeb427a/call-align/shard-1/execution/stdout, STDERR=/wynton/home/ahituv/wpratcher/rna-seq-pipeline/rna/504acb6a-03c0-4bc5-ab1c-af345eeb427a/call-align/shard-1/execution/stderr
STDERR_CONTENTS=
2020-02-27 14:16:34,940 | INFO | __main__: Creating a single-ended aligner.
2020-02-27 14:16:34,981 | INFO | __main__: running STAR command STAR --genomeDir out --readFilesIn /wynton/home/ahituv/wpratcher/rna-seq-pipeline/rna/504acb6a-03c0-4bc5-ab1c-af345eeb427a/call-align/shard-1/inputs/-945160394/rep2_ENCSR510QZW_chr19only_10000_reads.fastq.gz --readFilesCommand zcat --runThreadN 2 --genomeLoad NoSharedMemory --outFilterMultimapNmax 20 --alignSJoverhangMin 8 --alignSJDBoverhangMin 1 --outFilterMismatchNmax 999 --outFilterMismatchNoverReadLmax 0.04 --alignIntronMin 20 --alignIntronMax 1000000 --alignMatesGapMax 1000000 --outSAMheaderCommentFile COfile.txt --outSAMheaderHD @HD VN:1.4 SO:coordinate --outSAMunmapped Within --outFilterType BySJout --outSAMattributes NH HI AS NM MD --outSAMstrandField intronMotif --outSAMtype BAM SortedByCoordinate --quantMode TranscriptomeSAM --sjdbScore 1 --limitBAMsortRAM 4000000000
2020-02-27 14:17:25,616 | INFO | __main__: Transcriptome bam is not rsem-sorted.
2020-02-27 14:17:25,732 | INFO | __main__: Running convert-sam-for-rsem Aligned.toTranscriptome.out.bam rep2SE_unstranded_anno
2020-02-27 14:17:27,615 | INFO | __main__: Getting samtools flagstats for /wynton/home/ahituv/wpratcher/rna-seq-pipeline/rna/504acb6a-03c0-4bc5-ab1c-af345eeb427a/call-align/shard-1/execution/rep2SE_unstranded_genome.bam
2020-02-27 14:17:27,674 | INFO | __main__: Getting samtools flagstats for /wynton/home/ahituv/wpratcher/rna-seq-pipeline/rna/504acb6a-03c0-4bc5-ab1c-af345eeb427a/call-align/shard-1/execution/rep2SE_unstranded_anno.bam

rna.kallisto Failed. SHARD_IDX=0, RC=None, JOB_ID=5038, RUN_START=2020-02-27T22:15:24.498Z, RUN_END=2020-02-27T22:15:56.672Z, STDOUT=/wynton/home/ahituv/wpratcher/rna-seq-pipeline/rna/504acb6a-03c0-4bc5-ab1c-af345eeb427a/call-kallisto/shard-0/execution/stdout, STDERR=/wynton/home/ahituv/wpratcher/rna-seq-pipeline/rna/504acb6a-03c0-4bc5-ab1c-af345eeb427a/call-kallisto/shard-0/execution/stderr
STDERR_CONTENTS=
2020-02-27 14:15:26,547 | INFO | __main__: Running kallisto command: kallisto quant -i /wynton/home/ahituv/wpratcher/rna-seq-pipeline/rna/504acb6a-03c0-4bc5-ab1c-af345eeb427a/call-kallisto/shard-0/inputs/-945160394/Homo_sapiens.GRCh38.cdna.all.chr19_ERCC_phix_k31_kallisto.idx -o kallisto_out -t 2 --plaintext --single -l 250 -s 10.0 /wynton/home/ahituv/wpratcher/rna-seq-pipeline/rna/504acb6a-03c0-4bc5-ab1c-af345eeb427a/call-kallisto/shard-0/inputs/-945160394/rep1_ENCSR510QZW_chr19only_10000_reads.fastq.gz

[quant] fragment length distribution is truncated gaussian with mean = 250, sd = 10
[index] k-mer length: 31
[index] number of targets: 11,567
[index] number of k-mers: 6,247,960
[index] number of equivalence classes: 50,703
[quant] running in single-end mode
[quant] will process file 1: /wynton/home/ahituv/wpratcher/rna-seq-pipeline/rna/504acb6a-03c0-4bc5-ab1c-af345eeb427a/call-kallisto/shard-0/inputs/-945160394/rep1_ENCSR510QZW_chr19only_10000_reads.fastq.gz
[quant] finding pseudoalignments for the reads ... done
[quant] processed 10,000 reads, 8,865 reads pseudoaligned
[   em] quantifying the abundances ... done
[   em] the Expectation-Maximization algorithm ran for 657 rounds

rna.kallisto Failed. SHARD_IDX=1, RC=None, JOB_ID=5186, RUN_START=2020-02-27T22:15:26.499Z, RUN_END=2020-02-27T22:15:57.854Z, STDOUT=/wynton/home/ahituv/wpratcher/rna-seq-pipeline/rna/504acb6a-03c0-4bc5-ab1c-af345eeb427a/call-kallisto/shard-1/execution/stdout, STDERR=/wynton/home/ahituv/wpratcher/rna-seq-pipeline/rna/504acb6a-03c0-4bc5-ab1c-af345eeb427a/call-kallisto/shard-1/execution/stderr
STDERR_CONTENTS=
2020-02-27 14:15:28,585 | INFO | __main__: Running kallisto command: kallisto quant -i /wynton/home/ahituv/wpratcher/rna-seq-pipeline/rna/504acb6a-03c0-4bc5-ab1c-af345eeb427a/call-kallisto/shard-1/inputs/-945160394/Homo_sapiens.GRCh38.cdna.all.chr19_ERCC_phix_k31_kallisto.idx -o kallisto_out -t 2 --plaintext --single -l 250 -s 10.0 /wynton/home/ahituv/wpratcher/rna-seq-pipeline/rna/504acb6a-03c0-4bc5-ab1c-af345eeb427a/call-kallisto/shard-1/inputs/-945160394/rep2_ENCSR510QZW_chr19only_10000_reads.fastq.gz

[quant] fragment length distribution is truncated gaussian with mean = 250, sd = 10
[index] k-mer length: 31
[index] number of targets: 11,567
[index] number of k-mers: 6,247,960
[index] number of equivalence classes: 50,703
[quant] running in single-end mode
[quant] will process file 1: /wynton/home/ahituv/wpratcher/rna-seq-pipeline/rna/504acb6a-03c0-4bc5-ab1c-af345eeb427a/call-kallisto/shard-1/inputs/-945160394/rep2_ENCSR510QZW_chr19only_10000_reads.fastq.gz
[quant] finding pseudoalignments for the reads ... done
[quant] processed 10,000 reads, 8,919 reads pseudoaligned
[   em] quantifying the abundances ... done
[   em] the Expectation-Maximization algorithm ran for 651 rounds 

I just want to know what is wrong

**Comment by ottojolanki** [comment]
Hello @wpratcher, and thank you for your interest in our pipeline. Could you please share with me a few bits of information so that I can get debugging going. 
1. Could you share with me the complete input json file you are using?
2. What platform are you trying to run the pipeline on?
3. What command are you invoking the pipeline with? (are you using caper? if you are not, you should seriously consider doing so.)
Thanks!

**Comment by wpratcher** [comment]
@ottojolanki Thank you for your quick replay:
first I have attached the input file in this image: 
<img width="1440" alt="Screen Shot 2020-02-27 at 2 47 44 PM" src="https://user-images.githubusercontent.com/60943100/75494961-40692d80-5972-11ea-8332-0b0536aafeee.png">

second, I am trying to run a normal RNA-seq on SE samples, but working with the test data that I am following from the manual

third, I am using caper which works as from the result, but keep getting an error in the kallisto part of the result

fourth, the master version is the one I am working with. 

thank you again

**Comment by ottojolanki** [comment]
Thank you for the info @wpratcher. Could you additionally let me know what platform are you running on, and also share with me your caper configuration file?

**Comment by wpratcher** [comment]
@ottojolanki  I am using Terminal on Mac OS X using the 0.6.4 version of Caper

**Comment by ottojolanki** [comment]
@wpratcher Thank you for the information. Could you show me the exact command line you invoke the caper run with, just to make sure? From the stdout snippet you posted above it looks like something actually runs but then fails for some reason. One thing that would be worth checking is the amount of memory you allow to the Docker engine. I run the same input with caper 0.6.4 on mac with 8 cpus and 8GB given to docker and it works fine. Docker stepping over its allowance could cause some rather cryptic failures.

**Comment by wpratcher** [comment]
@ottojolanki the caper line goes exactly in the instructions: 
caper run rna-seq-pipeline.wdl -i test/test_workflow/SE_unstranded_input.json --singularity

and i am unsure on the memory as I am running it based on a cluster that was generated at the lab i work for. But to test how you do since you run on the same system, how could I adjust the values?

**Comment by ottojolanki** [comment]
@wpratcher ohhh, you are not running on docker. I recommend you do so, because that is faster and the "canonical" way of running. Also there is no reason to use singularity as you are on your mac. You can change the memory settings in your Docker engine preferences. If you still want to keep using singularity, you should consult their documentation and see how the memory settings work.

**Comment by wpratcher** [comment]
@ottojolanki Okay i will try with docker and report back if it works. Thank you!

**Comment by wpratcher** [comment]
@ottojolanki With the docker I am still having issues :
 caper run rna-seq-pipeline.wdl -i input.json -m testrun_metadata.json --docker
[CaperURI] read from local, src: /Users/WilliamPratcherII/Downloads/app/rna-seq-pipeline/input.json
Traceback (most recent call last):
  File "/Users/WilliamPratcherII/anaconda3/bin/caper", line 13, in <module>
    main()
  File "/Users/WilliamPratcherII/anaconda3/lib/python3.6/site-packages/caper/caper.py", line 1267, in main
    c.run()
  File "/Users/WilliamPratcherII/anaconda3/lib/python3.6/site-packages/caper/caper.py", line 197, in run
    input_file = self.__create_input_json_file(tmp_dir)
  File "/Users/WilliamPratcherII/anaconda3/lib/python3.6/site-packages/caper/caper.py", line 681, in __create_input_json_file
    uri_type=uri_type, uri_exts=self._deepcopy_ext)
  File "/Users/WilliamPratcherII/anaconda3/lib/python3.6/site-packages/caper/caper_uri.py", line 811, in deepcopy
    uri_type=uri_type, uri_exts=uri_exts)
  File "/Users/WilliamPratcherII/anaconda3/lib/python3.6/site-packages/caper/caper_uri.py", line 776, in __deepcopy_json
    org_d = json.loads(contents, object_pairs_hook=OrderedDict)
  File "/Users/WilliamPratcherII/anaconda3/lib/python3.6/json/__init__.py", line 367, in loads
    return cls(**kw).decode(s)
  File "/Users/WilliamPratcherII/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/WilliamPratcherII/anaconda3/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 3 column 139 (char 172)

this is the output I keep getting. 

here is the code I used: 
{
    "rna.endedness" : "single",
    "rna.fastqs_R1" : "[/Users/WilliamPratcherII/Downloads/app/rna-seq-pipeline/test_data/rep1_ENCSR510QZW_chr19only_10000_reads.fastq.gz"],["/Users/WilliamPratcherII/Downloads/app/rna-seq-pipeline/test_$
    "rna.bamroot" : "SE_unstranded",
    "rna.align_index" : "/Users/WilliamPratcherII/Downloads/app/rna-seq-pipeline/test_data/GRCh38_v24_ERCC_phiX_starIndex_chr19only.tgz",
    "rna.rsem_index" : "/Users/WilliamPratcherII/Downloads/app/rna-seq-pipeline/test_data/GRCh38_v24_ERCC_phiX_rsemIndex_chr19only.tgz",
    "rna.kallisto_index" : "/Users/WilliamPratcherII/Downloads/app/rna-seq-pipeline/test_data/Homo_sapiens.GRCh38.cdna.all.chr19_ERCC_phix_k31_kallisto.idx",
    "rna.strandedness" : "unstranded",
    "rna.strandedness_direction" : "unstranded",
    "rna.chrom_sizes" : "/Users/WilliamPratcherII/Downloads/app/rna-seq-pipeline/test_data/GRCh38_EBV.chrom.sizes",
    "rna.align_ncpus" : 2,
    "rna.align_ramGB" : 4,
    "rna.rsem_ncpus" : 2,
    "rna.rsem_ramGB" : 4,
    "rna.kallisto_number_of_threads" : 2,
    "rna.kallisto_ramGB" : 4,
    "rna.kallisto_fragment_length" : 250,
    "rna.kallisto_sd_of_fragment_length" : 10,
    "rna.rna_qc_tr_id_to_gene_type_tsv" : "/Users/WilliamPratcherII/Downloads/app/rna-seq-pipeline/transcript_id_to_gene_type_mappings/gencodeV24pri-tRNAs-ERCC-phiX.transcript_id_to_genes.tsv",
    "rna.bam_to_signals_ncpus" : 1,
    "rna.bam_to_signals_ramGB" : 2,
    "rna.align_disk" : "local-disk 20 HDD",
    "rna.kallisto_disk" : "local-disk 20 HDD",
    "rna.rna_qc_disk" : "local-disk 20 HDD",
    "rna.bam_to_signals_disk" : "local-disk 20 HDD",
    "rna.mad_qc_disk" : "local-disk 20 HDD",
    "rna.rsem_disk" : "local-disk 20 HDD"

}

So I am not sure what I am still doing wrong.

**Comment by leepc12** [comment]
Your input JSON is malformed.
```
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 3 column 139 (char 172)
```

**Comment by wpratcher** [comment]
@leepc12 How may I correct the malformed json?

**Comment by leepc12** [comment]
Please see line 3.
```
{
"rna.endedness" : "single",
"rna.fastqs_R1" : "[/Users/WilliamPratcherII/Downloads/app/rna-seq-pipeline/test_data/rep1_ENCSR510QZW_chr19only_10000_reads.fastq.gz"],["/Users/WilliamPratcherII/Downloads/app/rna-seq-pipeline/test_$
"rna.bamroot" : "SE_unstranded",
```

**Comment by wpratcher** [comment]
Still shows error. @leepc12

**Comment by leepc12** [comment]
If you got the same JSON error then your JSON is still invalid. Use any online JSON validator to fix your problem.
