### ISSUE TITLE
call-kallisto/shard-1/attempt-2/execution/script: line 23: python3: command not found

### ISSUE THREAD

**Issue by byee4** [ENCODE-DCC/rna-seq-pipeline#93]
Hi!

I'm trying to run the rna-seq-pipeline with caper + singularity and am hitting a 'python3 not found' upon execution of the "PE_stranded" manifest. I'm attaching the manifest/command/cromwell.out output, could someone help me identify the cause of this error?

Thank you!

[rna-seq-pipeline-1.2.4-log.txt](https://github.com/ENCODE-DCC/rna-seq-pipeline/files/8335226/rna-seq-pipeline-1.2.4-log.txt)

**Comment by leepc12** [comment]
I found `--singularity docker://ubuntu:latest` in your command line. Please remove `docker://ubuntu:latest` and use `--singularity` as a flag then Caper will find/use pipeline's singularity image defined in WDL (https://github.com/ENCODE-DCC/rna-seq-pipeline/blob/dev/rna-seq-pipeline.wdl#L78(.

**Comment by byee4** [comment]
Thanks for the quick response! Removing the default image gets past this error, however there is a new one. I'm attaching the logs in case it is helpful:
[cromwell-plus-stderr.txt](https://github.com/ENCODE-DCC/rna-seq-pipeline/files/8335976/cromwell-plus-stderr.txt)

**Comment by leepc12** [comment]
Please post your input JSON. No whitespace is allowed in file names.

**Comment by byee4** [comment]
Here is my JSON file:
[PE_stranded_input.txt](https://github.com/ENCODE-DCC/rna-seq-pipeline/files/8336677/PE_stranded_input.txt)

**Comment by leepc12** [comment]
What is your caper command line?
If you used `--singularity encodedcc/rna-seq-pipeline:1.2.4` then try with `--singularity` only.

**Comment by byee4** [comment]
Hi, I used the same command as before, just without specifying ubuntu

```
  caper run \
  --conf /home/bay001/.caper/default_local.conf \
  rna-seq-pipeline.wdl \
  --local-loc-dir ${INTERM} \
  --local-out-dir ${OUTDIR} \
  -i PE_stranded_input.json \
  --debug \
  --singularity
```

**Comment by leepc12** [comment]
We will be looking into this. Until it's fixed, please pull the singularity image and then define it in the arguments.

```bash
$ singularity pull docker://encodedcc/rna-seq-pipeline:1.2.4

# find the pulled image
$ ls -l rna-seq-pipeline_1.2.4.sif

# test it
$ singularity exec rna-seq-pipeline_1.2.4.sif echo hello

# get the absolute path of the sif file
$ pwd
```

Then define the SIF file in your input JSON.
```javascript
{
    "rna.singularity": "/PATH/TO/rna-seq-pipeline_1.2.4.sif"
}
```

**Comment by byee4** [comment]
Hi and thank you! It seems like the input JSON does not validate or accept the "rna.singularity" param?

```
...
2022-03-26 09:28:28,980|caper.cromwell|INFO| Validating WDL/inputs/imports with Womtool...
Traceback (most recent call last):
  File "/projects/ps-yeolab4/software/yeolabconda3/envs/caper-2.1.3/bin/caper", line 13, in <module>
    main()
  File "/projects/ps-yeolab4/software/yeolabconda3/envs/caper-2.1.3/lib/python3.10/site-packages/caper/cli.py", line 705, in main
    return runner(parsed_args, nonblocking_server=nonblocking_server)
  File "/projects/ps-yeolab4/software/yeolabconda3/envs/caper-2.1.3/lib/python3.10/site-packages/caper/cli.py", line 249, in runner
    subcmd_run(c, args)
  File "/projects/ps-yeolab4/software/yeolabconda3/envs/caper-2.1.3/lib/python3.10/site-packages/caper/cli.py", line 379, in subcmd_run
    thread = caper_runner.run(
  File "/projects/ps-yeolab4/software/yeolabconda3/envs/caper-2.1.3/lib/python3.10/site-packages/caper/caper_runner.py", line 462, in run
    self._cromwell.validate(wdl=wdl, inputs=inputs, imports=imports)
  File "/projects/ps-yeolab4/software/yeolabconda3/envs/caper-2.1.3/lib/python3.10/site-packages/caper/cromwell.py", line 154, in validate
    raise WomtoolValidationFailed(
caper.cromwell.WomtoolValidationFailed: RC=1
STDERR=WARNING: Unexpected input provided: rna.singularity (expected inputs: [rna.bam_to_signals_ncpus, rna.align_ncpus, rna.rsem_ncpus, rna.rna_qc_tr_id_to_gene_type_tsv, rna.reference_transcriptome, rna.kallisto_sd_undefined, rna.pbam_ncpus, rna.endedness, rna.pbam_ramGB, rna.rnd_seed, rna.bam_to_signals_ramGB, rna.bam_to_signals.null, rna.reference_genome, rna.align_ramGB, rna.kallisto_index, rna.align_disk, rna.reference_genome_decompressed.output_filename, rna.kallisto_disk, rna.reference_transcriptome_decompressed.output_filename, rna.mad_qc_disk, rna.rsem_index, rna.kallisto_fragment_length_undefined, rna.reference_annotations, rna.fastqs_R2, rna.pbam_disks, rna.kallisto_fragment_length, rna.chrom_sizes, rna.rsem_ramGB, rna.rsem_disk, rna.bam_to_signals_disk, rna.strandedness_direction, rna.align_index, rna.produce_pbams, rna.strandedness, rna.kallisto_sd_of_fragment_length, rna.bamroot, rna.fastqs_R1, rna.kallisto_ramGB, rna.kallisto_number_of_threads, rna.rna_qc_disk, rna.run_kallisto])
```

**Comment by leepc12** [comment]
What is your pipeline version?
```bash
$ cat rna-seq-pipeline.wdl | grep version:
        version: "v1.2.1"
```

**Comment by byee4** [comment]
```
rna-seq-pipeline-1.2.4]$ cat rna-seq-pipeline.wdl | grep version:
        version: "1.2.4"
```

**Comment by byee4** [comment]
Closing this, pulling the latest image from docker solves this problem.
